### ISSUE TITLE
legacy api @RCSB is no longer supported 

### ISSUE THREAD

**Issue by rkrutyholowa** [hiteshpatel379/PyWATER#12]
Dear Developers, 

Running an exemple ("pywater 4lyw, A, 95") returns **"HTTPError: HTTP Error 404: Not Found"**.

> Traceback (most recent call last):
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\site-packages\pmg_tk\startup\pywater.py", line 973, in toPyWATER
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\site-packages\pmg_tk\startup\pywater.py", line 748, in FindConservedWaters
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\site-packages\pmg_tk\startup\pywater.py", line 665, in isXray
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\MaxPlanck_Lab1\PyMOL\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

It seems, that RCSB no longer supports legacy APIs (since 09.12.2021).
[https://www.rcsb.org/pdb/rest/customReport?pdbids=4lyw&customReportColumns=entityId&service=wsdisplay&format=xml&ssa=n](https://www.rcsb.org/pdb/rest/customReport?pdbids=4lyw&customReportColumns=entityId&service=wsdisplay&format=xml&ssa=n)
Please, update the urllib call to make things work again.

Thanks in advance,
Rościsław

**Comment by hahadg** [comment]
I met the same issue, anyone solved?

**Comment by yoavatsmonraz** [comment]
I also have the same issue, help please ?

**Comment by hiteshpatel379** [comment]
Closing as resolved by the recent RCSB API modernization. PyWATER no longer uses the retired RCSB customReport/XML endpoints that caused these HTTP 404/XML parsing errors; the plugin now uses the current RCSB Data/Search APIs. Please reopen or file a new issue if this still occurs with the latest master.
