### ISSUE TITLE
Error: PyWater installed but failed to initiate

### ISSUE THREAD

**Issue by jaydeepsb** [hiteshpatel379/PyWATER#13]
I downloaded the .py script locally and installed in Pymol2 as below,
Within PyMol2 -> Plugins -> Plugin-manager -> Install new plugins -> Install from local file

I got an error stating "PyWater installed successfully but failed to initiate"

I restarted PyMol. tried to access pywater command, but got error command not recognized.

**Comment by DipBobDar** [comment]
I am having the same issue...plus i can initiate pywater from command line but it shows the following errors

PyMOL>pywater 1SUS, A, 95
Traceback (most recent call last):
  File "C:\Users\ddhar\AppData\Local\pymol\lib\site-packages\pmg_tk\startup\pywater.py", line 973, in toPyWATER
    FindConservedWaters(selectedStruturePDB,selectedStrutureChain,seq_id,resolution,refinement,user_def_list,clustering_method,inconsistency_coefficient,prob)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\site-packages\pmg_tk\startup\pywater.py", line 748, in FindConservedWaters
    if not isXray(selectedStruturePDB):
  File "C:\Users\ddhar\AppData\Local\pymol\lib\site-packages\pmg_tk\startup\pywater.py", line 665, in isXray
    expInfoURL = urllib.urlopen(expInfoAddress)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 555, in error
    result = self._call_chain(*args)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\ddhar\AppData\Local\pymol\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by hiteshpatel379** [comment]
Closing as outdated/superseded. The reported traceback in the later comment came from the retired RCSB customReport/XML endpoint, which has now been replaced with current RCSB Data/Search APIs. The plugin initialization path has also been modernized for PyMOL's Qt plugin API. Please open a new issue with a fresh traceback if this still occurs on latest master.
